site_name: NW.js 0.35.2 中文参考文档
theme: readthedocs
use_directory_urls: true
site_url: https://nwjs.liuxp.me
site_author: 刘小平
repo_url: https://github.com/lxp135/NW.jsCnDocs
copyright: NW.js中文参考文档由<a href="https://liuxp.me">刘小平</a>提供，项目托管在<a href="https://github.com/lxp135/NW.jsCnDocs">GitHub</a>，欢迎您参与翻译。<script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js?id=CDqGooQbS8dts6eI&ck=CDqGooQbS8dts6eI"></script>

nav:
- '首页': 'index.md'
- '用户手册':
  - '快速开始': 'For Users/Getting Started.md'
  - '使用开发者工具调试': 'For Users/Debugging with DevTools.md'
  - '打包与发布': 'For Users/Package and Distribute.md'
  - 'FAQ': 'For Users/FAQ.md'
  - '迁移':
    - '0.12升级0.13': 'For Users/Migration/From 0.12 to 0.13.md'
  - '进阶':
    - '编译版本': 'For Users/Advanced/Build Flavors.md'
    - '内容验证': 'For Users/Advanced/Content Verification.md'
    - '自定义菜单': 'For Users/Advanced/Customize Menubar.md'
    - '在NW.js中使用JavaScript上下文': 'For Users/Advanced/JavaScript Contexts in NW.js.md'
    - '保护JavaScript源代码': 'For Users/Advanced/Protect JavaScript Source Code.md'
    - 'NW.js的安全性': 'For Users/Advanced/Security in NW.js.md'
    - '提交到Mac应用商店': 'For Users/Advanced/Support for Mac App Store.md'
    - '使用ChromeDriver测试': 'For Users/Advanced/Test with ChromeDriver.md'
    - '透明窗口': 'For Users/Advanced/Transparent Window.md'
    - '在NW.js中使用Flash插件': 'For Users/Advanced/Use Flash Plugin.md'
    - '在NW.js中使用NaCl': 'For Users/Advanced/Use NaCl in NW.js.md'
    - '在NW.js中使用原生Node.js模块': 'For Users/Advanced/Use Native Node Modules.md'
    - '自动更新': 'For Users/Advanced/Autoupdates.md'
- '开发者手册':
  - '构建 NW.js': 'For Developers/Building NW.js.md'
  - '为NW.js贡献代码': 'For Developers/Contributing to NW.js.md'
  - '打开专有编解码器': 'For Developers/Enable Proprietary Codecs.md'
  - '资源列表': 'For Developers/Repositories.md'
  - '了解崩溃机制': 'For Developers/Understanding Crash Dump.md'
  - '为NW.js编写文档': 'For Developers/Writing Documents for NW.js.md'
  - '为NW.js编写测试用例': 'For Developers/Writing Test Cases for NW.js.md'
  - '贡献者列表': 'For Developers/Contributors of Documents.md'
- '参考资料':
  - 'App': 'References/App.md'
  - 'DOM的变化': 'References/Changes to DOM.md'
  - 'Node的变化': 'References/Changes to Node.md'
  - '剪切板': 'References/Clipboard.md'
  - '命令行参数': 'References/Command Line Options.md'
  - 'Chrome扩展API': 'References/Chrome Extension APIs.md'
  - '配置文件': 'References/Manifest Format.md'
  - '菜单': 'References/Menu.md'
  - '菜单项': 'References/MenuItem.md'
  - '屏幕': 'References/Screen.md'
  - 'Shell': 'References/Shell.md'
  - '快捷键': 'References/Shortcut.md'
  - '系统托盘': 'References/Tray.md'
  - 'webview标签': 'References/webview Tag.md'
  - 'Window': 'References/Window.md'

markdown_extensions:
    - markdown.extensions.toc
    - markdown.extensions.admonition
    - markdown.extensions.smarty
    - markdown.extensions.nl2br
    - markdown.extensions.codehilite:
        guess_lang: false